version: '3.1'
services:
  walking-mysql:
    container_name: walking-mysql8
    image: mysql/mysql-server:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", "--max_connections=2048", "--wait_timeout=3600" ]
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

  walking-adminer: # mysql web admin
    container_name: walking-adminer
    image: adminer:4
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=walking-mysql8
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce

  walking-minio:
    container_name: walking-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    shm_size: '1gb'
    environment:
      - MINIO_ACCESS_KEY=thisisroot
      - MINIO_SECRET_KEY=thisisroot
      - MINIO_ROOT_USER=thisisroot
      - MINIO_ROOT_PASSWORD=thisisroot
      - MINIO_REGION_NAME=ap-northeast-2
    command: server /data --console-address ":9001"